### ISSUE TITLE
Won't build on Haiku

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/JoystickUtilizer#1]
After attempt to build JoystickUtilizer on Haiku (hrev51291 gcc2_hybtid), I got this batch of errors:
http://sprunge.us/MJiR

However would be fine to convert the *.proj files to makefile.

**Comment by humdingerb** [comment]
Fixed with 506772cb6a3847dcd58161796ed0c62845d1e487.
I'll add a recipe for it to haikuports.
